import { mkdir, readFile, writeFile, cp, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';

const root = resolve(import.meta.dirname, '..');
const out = resolve(root, 'dist');
const base = process.env.BASE_PATH || '/';
if (!/^\/(?:[a-zA-Z0-9_-]+\/)*$/.test(base)) throw new Error('BASE_PATH must start and end with / and contain URL path segments.');
const origin = process.env.SITE_ORIGIN || 'https://thejhyefactor.github.io';
const measurementId = process.env.GA_MEASUREMENT_ID || 'G-C6ZMWP9EX9';
if (!/^G-[A-Z0-9]+$/.test(measurementId)) throw new Error('Invalid GA_MEASUREMENT_ID');
const repo = 'https://github.com/TheJhyeFactor/Wixal';
const docs = `${repo}/blob/main/docs`;
const engineVersion = await readFile(resolve(root, '../native/engine/wixal/__init__.py'), 'utf8');
const version = engineVersion.match(/^VERSION = "([0-9.]+-alpha\.[0-9]+)"$/m)?.[1];
if (!version) throw new Error('Website requires a native alpha release version.');

const versionLabel = version.replace('-alpha.', ' Alpha ');
const release = `${repo}/releases/tag/v${version}`;
const zip = `${repo}/releases/download/v${version}/Wixal-${version}-macOS-arm64.zip`;
const url = path => base + path;
const assetHashes = new Map(await Promise.all(['styles.css', 'site.js', 'analytics.js', 'stats.js', 'totals.js', 'assets/social-card.png', 'assets/native-workspace.png', 'assets/wixal-demo.mp4', 'assets/wixal-demo-poster.jpg'].map(async path => [path, createHash('sha256').update(await readFile(resolve(root, path.startsWith('assets/') ? 'public' : 'src', path))).digest('hex').slice(0, 10)])));
const assetUrl = path => `${url(path)}?v=${assetHashes.get(path)}`;
const arrow = '<span aria-hidden="true">↗</span>';
const external = arrow;
const link = (href, label, icon = arrow, cls = '') => `<a class="text-link ${cls}" href="${href}">${label}${icon}</a>`;
const button = (href, label = 'Download for Mac', cls = '') => `<a class="button ${cls}" href="${href}">${label}</a>`;
function appearance() { return `<div class="appearance" role="group" aria-label="Website appearance"><button data-theme="light" aria-label="Light mode" aria-pressed="true">☀</button><button data-theme="dark" aria-label="Dark mode" aria-pressed="false">☾</button></div>`; }
function header() { return `<a class="skip-link" href="#main">Skip to content</a><header class="header container"><a class="brand" href="${url('')}" aria-label="Wixal home">wixal</a><nav aria-label="Main navigation"><a href="${url('resources/')}">Guides</a><a href="${repo}">GitHub</a>${button(url('download/'), 'Download', 'small')}</nav></header>`; }
function footer() { return `<footer class="footer container"><a class="brand" href="${url('')}">wixal</a><nav aria-label="Footer navigation"><a href="${url('privacy/')}">Privacy</a><button class="privacy-settings" data-privacy-settings>Analytics preferences</button><a href="${url('stats/')}">Download stats</a><a href="${repo}/blob/main/THIRD_PARTY_NOTICES.md">Credits</a><a href="${repo}/issues">Report an issue</a></nav>${appearance()}</footer>`; }
function totals() { return `<div class="site-totals"><div><strong data-download-total aria-live="polite">—</strong><span>Release downloads</span><small>DMG & ZIP · all releases</small></div><div><strong data-active-users-total aria-live="polite">—</strong><span>Website visitors</span><small>Last 30 days · opted-in visitors</small></div></div>`; }
const heading = (title, copy) => `<section class="page-hero container"><h1>${title}</h1><p class="hero-subtitle">${copy}</p></section>`;
const row = (id, title, copy, href, label) => `<article class="capability" id="${id}"><h3>${title}</h3><div><p>${copy}</p>${href ? link(href,label) : ''}</div></article>`;
const home = `<section class="hero container">
  <p class="eyebrow">Native alpha · Wixal for Mac</p>
  <h1>Local AI for<br>your projects.</h1>
  <p class="hero-subtitle">Chat with local models, build agents and run workflows. Inspect the tools they use and the results they return.</p>
  <div class="hero-actions">${button(zip,'Download for macOS')}${link(repo,'View on GitHub')}</div>
  <p class="release-meta">${version} · Apple Silicon · macOS 14+ · Not notarised</p>
  <figure class="demo-preview">
    <video data-demo controls loop muted playsinline preload="auto" width="1600" height="900" poster="${assetUrl('assets/wixal-demo-poster.jpg')}" aria-label="Wixal installation and product demo" aria-describedby="demo-description">
      <source src="${assetUrl('assets/wixal-demo.mp4')}" type="video/mp4">
      <p><a href="${assetUrl('assets/wixal-demo.mp4')}">Watch the Wixal demo</a></p>
    </video>
    <figcaption><span>Setup → local models → project tools → cybersecurity</span><span class="demo-actions"><span>46 seconds</span><button data-demo-playback hidden aria-label="Play demo">Play</button></span></figcaption>
    <p class="sr-only" id="demo-description">Animated command-line setup shows the release ZIP downloading, extracting and opening. Captured native Wixal workflows then show gpt-oss:20b reading a project README, completed tool activity and a cybersecurity baseline assessment of an authorised local website. The setup progress is illustrated; the app results are captured from actual local runs. The silent demo plays automatically and loops while visible. Use Pause to stop it. With reduced motion enabled, it starts only when you press Play.</p>
  </figure>
</section>
<section class="section container home-features" aria-label="Inside Wixal">
  <article id="models"><h2>Local models</h2><p>Choose a model that runs on your Mac.</p>${link(url('models/'),'Models & connections')}</article>
  <article id="projects"><h2>Project context</h2><p>Keep files, conversations and tools together.</p>${link(url('product/'),'Inside the workspace')}</article>
  <article id="security"><h2>Cybersecurity</h2><p>Investigate authorised targets and review retained evidence.</p>${link(url('product/#security'),'Security workspace')}</article>
</section>
<section class="section container native-section" id="whats-new"><div><p class="eyebrow">${versionLabel}</p><h2>Keep the work moving.</h2></div><div><p>Queue tasks while an agent runs, resume in the original project, and keep your draft when a save needs correction. Paused and interrupted work stays visible, with command evidence retained for review.</p>${link(release,'Explore what’s new')}</div></section>
<section class="section container native-section"><div><p class="eyebrow">Public alpha</p><h2>One native app.</h2></div><div><p>The current download uses SwiftUI, AppKit and a persistent Python agent engine. It includes the Agents workspace, recurring tasks, skills, project memory and a cybersecurity workspace.</p><p>This is an early release. Local tool workflows have been tested with gpt-oss:20b. Remote execution, messaging gateways, automatic updates and notarisation are still to come.</p>${link(release,'Alpha notes & limitations')}</div></section>`;
const product = `${heading('Your project, in context.','Files, conversations, agents and useful notes, close to the work.')}<section class="section container capabilities">${row('desktop','Native on your Mac','Open a project folder, attach useful files and work with a local model. The app uses SwiftUI and AppKit.',`${repo}/blob/main/native/README.md`,'Native guide')}${row('agents','Build reusable agents','Give an agent a purpose, instructions and a model. Set its authority and success criteria, then inspect tool activity and saved run history.',url('tools/'),'Agents & workflows')}${row('recovery','Keep a task moving','Queue and cancel pending work while an agent runs. Stop the selected run and resume in its original conversation and project. Rejected saves keep their drafts.',`${repo}/blob/main/docs/native-alpha.md#queue-stop-and-resume`,'Queue and recovery')}${row('workflows','Connect workflow steps','Build workflows with dependencies, bounded parallel execution and verifiable outputs. Inspect each step and retry recoverable failures.',`${repo}/blob/main/docs/native-alpha.md`,'Workflow guide')}${row('memory','Useful context','Save editable project notes, recall earlier work and review proposed lasting decisions. Memory changes stay visible.',`${repo}/blob/main/native/README.md#data-and-memory`,'Context and memory')}${row('terminal','A real terminal','Use an interactive project terminal or inspect agent commands with output, exit status and cancellation.',url('tools/#commands'),'Command workflows')}${row('security','Cybersecurity workspace','Record authorised scope, run bounded investigations and retain observations, evidence and findings. Validate results before treating them as security conclusions.',`${repo}/blob/main/docs/native-alpha.md#cybersecurity`,'Security scope')}</section>`;
const toolsPage = `${heading('Give the agent a task.','The model selects tools. You define the scope and review actions when required.')}<section class="section container capabilities">${row('selection','Model-selected tools','Tool-capable models see eligible tools and choose how to complete a task. Chat and Agents discover tools automatically. Agents use their authority policy; tool selection does not require user toggles.',`${repo}/blob/main/docs/native-alpha.md#agents-and-workflows`,'Agents and authority')}${row('files','Project files','Read and search files, create folders and review proposed writes or exact replacements within the selected project.',`${repo}/blob/main/native/README.md`,'Project boundaries')}${row('commands','Commands with evidence','Run a command, inspect output and exit status, send input or cancel it. Commands run with your Mac account’s access.',`${repo}/blob/main/docs/native-alpha.md`,'Tools and limits')}${row('web','Websites and APIs','Read source pages, inspect HTTP responses or work through reviewed WebKit browser actions. Network tools require a connection.',`${repo}/blob/main/native/README.md`,'Native tools')}${row('routines','Recurring work','Save calendar routines or interval schedules. Optional macOS background execution runs while the Mac is awake and pauses work that needs review.',`${repo}/blob/main/docs/native-alpha.md#recurring-tasks`,'Schedule behaviour')}${row('library','Inspect your tool library','Browse integrations, inspect installed providers and check readiness. Public managed downloads are gated while the signed catalogue is qualified; supported external installations remain available.',`${repo}/blob/main/docs/native-alpha.md#tool-library-and-reporting`,'Library status')}${row('external','MCP connections','Connect trusted local stdio or remote HTTP MCP servers. The agent can discover and call eligible connected tools.',`${repo}/blob/main/native/README.md`,'External connections')}${row('skills','Reusable skills','Load task-specific skills, save reusable procedures and compare candidate changes against explicit evaluation cases before promotion.',`${repo}/blob/main/docs/native-alpha.md`,'Skills and evaluations')}</section><section class="section container prompts"><h2>Try a small task.</h2><p>Open a project and choose a model that supports tools.</p><ul><li>Inspect this project’s README and explain where I should start.</li><li>Create a JSON summary of the project, then read it back to verify the fields.</li><li>Build a weekday routine to review this project’s notes at 09:15.</li></ul></section>`;
const modelPage = `${heading('Choose a model for the work.','Local inference, with a library you control.')}<section class="section container capabilities">${row('local','Wixal Local is included','Open Models to download a model or import compatible installed Ollama weights. No model weights are bundled.',`${repo}/blob/main/native/README.md`,'Native model setup')}${row('external','External Ollama','Connect a compatible server to use a separately managed model library.',`${repo}/blob/main/docs/native-alpha.md`,'Connection setup')}${row('capabilities','Match the task','Choose a tool-capable model for agents and a vision-capable model for images. The alpha’s real agent acceptance used gpt-oss:20b; other models may behave differently.',`${repo}/blob/main/native/AGENTS_COMPLETION_ACCEPTANCE_2026-10-08.md`,'Agent acceptance')}${row('performance','Measure on your Mac','Inspect generation speed, first-output timing and estimated memory fit. Throughput is separate from answer quality.',`${repo}/blob/main/native/README.md`,'Performance and limits')}${row('switching','Keep the conversation','Finish or stop a response before switching models. Readable context is retained while foreign private reasoning is excluded where required.',`${repo}/blob/main/native/README.md#data-and-memory`,'Context and memory')}</section>`;
const resourceRows = [
 ['Native alpha guide','Installation, agents, workflows and limitations.','native-alpha.md'],
 ['Alpha 3 release notes','Recovery, editing and evidence improvements.','release-0.7.10-alpha.3.md']
];
const resources = `${heading('A place to start.','Learn the app, find a workflow, or build on the source.')}<section class="section container resource-list">${resourceRows.map(([title,copy,path])=>`<a class="resource-item" href="${docs}/${path}"><h2>${title}</h2><p>${copy}</p><span aria-hidden="true">↗</span></a>`).join('')}<a class="resource-item" href="${repo}/blob/main/CONTRIBUTING.md"><h2>Contributing</h2><p>Report an issue or propose a change.</p><span aria-hidden="true">↗</span></a></section><section class="section container" id="releases"><h2>What’s changed.</h2><p>Read the release notes for ${version}, or browse the full changelog.</p><div class="hero-actions">${link(release,'Current alpha release')}${link(`${repo}/blob/main/CHANGELOG.md`,'Changelog')}</div></section>`;
const download = `${heading('Wixal native alpha.','One app for local models, agents and project work.')}<section class="section container download-layout"><div class="download-panel"><p class="eyebrow">Native alpha · ${versionLabel}</p><h2>Download for macOS.</h2><p>Apple Silicon · macOS 14 or newer</p><div class="hero-actions">${button(zip,'Download alpha ZIP')}</div><p>The local engine and Python runtime are included. Model weights download separately. Intel Mac, Windows and Linux builds are unavailable.</p>${link(release,'Release notes & SHA-256')}</div><div class="steps"><h2>Start with one project.</h2><ol><li>Extract the ZIP and move Wixal.app to Applications.</li><li>Open Wixal. If macOS blocks it, use System Settings → Privacy & Security → Open Anyway after reviewing the source and release notes.</li><li>Open Models and download a tool-capable model, import compatible weights or connect an external Ollama server.</li><li>Open a project folder. Chat, create an agent or build a workflow.</li></ol><p class="note">This alpha is ad-hoc signed and is not Developer ID signed or notarised. Updates are manual. Keep backups of important work.</p>${link(`${repo}/blob/main/docs/native-alpha.md`,'Native alpha guide')}</div></section><section class="section container native-section"><div><p class="eyebrow">Alpha boundaries</p><h2>What is still in progress.</h2></div><div><p>Remote execution, messaging and voice gateways, broader model compatibility, production security evaluation, sleep/wake/reboot acceptance and automatic updates remain incomplete.</p><p>Background routines require an awake Mac. Browser actions that require the desktop pause when it is closed. Model output and security findings require review.</p><p>Public managed-tool downloads and contributor GitHub sign-in are not configured in this alpha. See the guide for library status and reviewed manual bug reporting.</p><p>The earlier Electron releases remain in GitHub’s release history. This page downloads the current native alpha.</p>${link(`${repo}/issues`,'Report an alpha issue')}</div></section>`;
const privacy = `<section class="hero page-hero container"><h1>Website privacy.</h1><p class="hero-subtitle">Choose whether to share analytics.</p></section><section class="container section privacy-copy"><h2>Optional website analytics</h2><p>With your permission, this website uses Google Analytics to measure page visits, approximate visitor counts, referrals, and clicks on Wixal release downloads. Google receives browser and device information and processes your IP address. Analytics cookies distinguish browsers; these counts do not identify individual people.</p><p>Google Analytics loads only after you choose Allow analytics. You can change your choice using Analytics preferences in the footer. Declining keeps website analytics off. Downloads and all site pages remain available.</p><h2>Download clicks and GitHub downloads</h2><p>A download click records a request to open a release file. It does not prove a completed download or an installation. GitHub independently counts downloads of release assets, including direct links outside this site and repeated downloads.</p><h2>Public visitor total</h2><p>The site publishes only the aggregate active-user count for the last 30 days and the report update time. This count covers visitors who allow analytics and can be affected by browser blocking and Google processing delays. It updates daily.</p><h2>Your desktop workspace</h2><p>This website integration does not add telemetry to the Wixal app or send your projects, prompts, chats, model output, or notes to Google Analytics.</p><p><a class="inline-link" href="https://policies.google.com/privacy">Google privacy policy</a> · <a class="inline-link" href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub privacy statement</a></p></section>`;
const stats = `<section class="hero page-hero container"><h1>Wixal activity.</h1><p class="hero-subtitle">Downloads and website visitors.</p></section><section class="container section"><p class="note">These are downloads of DMG and ZIP release files, including direct GitHub downloads. Repeat downloads count again. Downloads do not equal unique users, installations, or active app users.</p><p role="status" data-stats-status>Loading GitHub release counts…</p><noscript><p>Enable JavaScript to load current counts, or view the release files on GitHub.</p></noscript>${totals()}<div class="stats-grid" style="grid-template-columns:1fr"><article class="download-panel"><h2 data-stats-latest data-release-tag="v${version}">—</h2><p>Current native alpha release</p></article></div><div class="stats-table-wrap"><table class="stats-table"><thead><tr><th>Release</th><th>DMG</th><th>ZIP</th><th>Total</th></tr></thead><tbody data-stats-rows></tbody></table></div><p class="note">Website visitors and download clicks are measured separately in the owner’s Google Analytics account when visitors allow analytics. Repository visitors and clones are available in GitHub Insights.</p><div class="hero-actions">${link(repo+'/releases','View releases',external)}${link(repo+'/tree/wixal-metrics','Daily GitHub report',external)}${link(repo+'/graphs/traffic','Repository traffic (owner access)',external)}</div></section>`;

const pages = [
 {path:'',title:'Wixal — Local AI for your projects',description:'A local AI workspace for Mac. Ask questions, work with project files and review model actions.',content:home},
 {path:'product/',title:'Workspace — Wixal',description:'Project files, conversations, context and commands in Wixal.',content:product},
 {path:'tools/',title:'Tools & workflows — Wixal',description:'Reviewed file, command, web and MCP tools.',content:toolsPage},
 {path:'models/',title:'Models & connections — Wixal',description:'Local models, imports and benchmarks on your Mac.',content:modelPage},
 {path:'resources/',title:'Guides — Wixal',description:'Get started with Wixal and explore its workflows.',content:resources},
 {path:'download/',title:'Download for Mac — Wixal',description:`Wixal ${version} native alpha download for Apple Silicon Macs running macOS 14 or newer.`,content:download},
 {path:'privacy/',title:'Website privacy — Wixal',description:'Optional website analytics and your choices.',content:privacy},
 {path:'stats/',title:'Download stats — Wixal',description:'GitHub release download counts and opted-in website visitors.',content:stats}
];
function document(page) {
  const canonical = `${origin}${url(page.path)}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.description}"><meta name="ga-measurement-id" content="${measurementId}"><meta name="theme-color" content="#f4f3ef"><meta property="og:type" content="website"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin}${assetUrl('assets/social-card.png')}"><meta name="twitter:card" content="summary_large_image"><link rel="canonical" href="${canonical}"><link rel="icon" href="${url('assets/favicon.svg')}" type="image/svg+xml"><script>try{const t=localStorage.getItem("wixal-site-theme");if(t==="dark"||t==="light")document.documentElement.dataset.theme=t}catch{}</script><link rel="stylesheet" href="${assetUrl('styles.css')}"><script type="module" src="${assetUrl('site.js')}"></script><script type="module" src="${assetUrl('analytics.js')}"></script>${page.path === 'stats/' ? `<script type="module" src="${assetUrl('totals.js')}"></script>` : ''}${page.path === 'stats/' ? `<script type="module" src="${assetUrl('stats.js')}"></script>` : ''}</head><body>${header(page.active)}<main id="main">${page.content}</main>${footer()}<aside class="analytics-choice" data-analytics-choice aria-label="Website analytics preferences" hidden><p>Allow optional analytics to help us understand website visits and download clicks? <a href="${url('privacy/')}">Privacy details</a></p><div><button data-analytics-deny>Decline</button><button data-analytics-allow>Allow analytics</button><button data-analytics-close aria-label="Close analytics preferences" hidden>Close</button></div></aside><dialog class="preview-dialog" aria-label="Wixal screenshot preview"><div class="preview-toolbar"><p>Inside Wixal</p><button data-preview-close aria-label="Close screenshot preview">Close ×</button></div><div class="preview-image"><img alt=""></div><p class="preview-description"></p></dialog></body></html>`;
}
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
await cp(resolve(root, 'public'), out, { recursive: true });
for (const file of ['styles.css', 'site.js', 'analytics.js', 'stats.js', 'totals.js']) await cp(resolve(root, 'src', file), resolve(out, file));
for (const page of pages) {
  await mkdir(resolve(out, page.path), { recursive: true });
  await writeFile(resolve(out, page.path, 'index.html'), document(page));
}
await writeFile(resolve(out, '404.html'), document({path:'404.html',title:'Page not found — Wixal',description:'Find your way back to Wixal.',content:`<section class="container error-page"><h1>This page has moved on.</h1><p>Let’s get you back to the workspace.</p>${button(url(''), 'Back to Wixal', '', arrow)}</section>`}));
await writeFile(resolve(out, '.nojekyll'), '');
await writeFile(resolve(out, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${origin}${url('sitemap.xml')}\n`);
await writeFile(resolve(out, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p => `<url><loc>${origin}${url(p.path)}</loc></url>`).join('')}</urlset>`);
await writeFile(resolve(out, 'assets/favicon.svg'), '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 124 110"><rect width="124" height="110" rx="16" fill="#26251e"/><path d="M9 19H25L41 66L54 31H68L82 66L98 19H114L92 87Q91 91 86 91H79Q74 91 73 87L61 54L49 87Q47 91 42 91H35Q31 91 29 87Z" fill="#f4f3ef"/></svg>');
console.log(`Built ${pages.length} Wixal pages at ${out} (base ${base}).`);
