import { mkdir, readFile, writeFile, cp, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';

const root = resolve(import.meta.dirname, '..');
const out = resolve(root, 'dist');
const base = process.env.BASE_PATH || '/';
if (!/^\/(?:[a-zA-Z0-9_-]+\/)*$/.test(base)) throw new Error('BASE_PATH must start and end with / and contain URL path segments.');
const origin = process.env.SITE_ORIGIN || 'https://thejhyefactor.github.io';
const measurementId = process.env.GA_MEASUREMENT_ID || 'G-C6ZMWP9EX9';
if (!/^G-[A-Z0-9]+$/.test(measurementId)) throw new Error('Invalid GA_MEASUREMENT_ID');
const repo = 'https://github.com/TheJhyeFactor/Wixal';
const docs = `${repo}/blob/main/docs`;
const version = '0.7.9';

const release = `${repo}/releases/tag/v${version}`;
const dmg = `${repo}/releases/download/v${version}/Wixal-${version}-macOS-arm64.dmg`;
const zip = `${repo}/releases/download/v${version}/Wixal-${version}-macOS-arm64.zip`;
const url = path => base + path;
const assetHashes = new Map(await Promise.all(['styles.css', 'site.js', 'analytics.js', 'stats.js', 'totals.js', 'assets/social-card.png', 'assets/native-workspace.png'].map(async path => [path, createHash('sha256').update(await readFile(resolve(root, path.startsWith('assets/') ? 'public' : 'src', path))).digest('hex').slice(0, 10)])));
const assetUrl = path => `${url(path)}?v=${assetHashes.get(path)}`;
const arrow = '<span aria-hidden="true">↗</span>';
const external = arrow;
const link = (href, label, icon = arrow, cls = '') => `<a class="text-link ${cls}" href="${href}">${label}${icon}</a>`;
const button = (href, label = 'Download for Mac', cls = '') => `<a class="button ${cls}" href="${href}">${label}</a>`;
function appearance() { return `<div class="appearance" role="group" aria-label="Website appearance"><button data-theme="light" aria-label="Light mode" aria-pressed="true">☀</button><button data-theme="dark" aria-label="Dark mode" aria-pressed="false">☾</button></div>`; }
function header() { return `<a class="skip-link" href="#main">Skip to content</a><header class="header container"><a class="brand" href="${url('')}" aria-label="Wixal home">wixal</a><nav aria-label="Main navigation"><a href="${url('resources/')}">Guides</a><a href="${repo}">GitHub</a>${button(url('download/'), 'Download', 'small')}</nav></header>`; }
function footer() { return `<footer class="footer container"><a class="brand" href="${url('')}">wixal</a><nav aria-label="Footer navigation"><a href="${url('privacy/')}">Privacy</a><button class="privacy-settings" data-privacy-settings>Analytics preferences</button><a href="${url('stats/')}">Download stats</a><a href="${repo}/blob/main/THIRD_PARTY_NOTICES.md">Credits</a><a href="${repo}/issues">Report an issue</a></nav>${appearance()}</footer>`; }
function totals() { return `<div class="site-totals"><div><strong data-download-total aria-live="polite">—</strong><span>Release downloads</span><small>DMG & ZIP · all releases</small></div><div><strong data-active-users-total aria-live="polite">—</strong><span>Website visitors</span><small>Last 30 days · opted-in visitors</small></div></div>`; }
const heading = (title, copy) => `<section class="page-hero container"><h1>${title}</h1><p class="hero-subtitle">${copy}</p></section>`;
const row = (id, title, copy, href, label) => `<article class="capability" id="${id}"><h3>${title}</h3><div><p>${copy}</p>${href ? link(href,label) : ''}</div></article>`;
const home = `<section class="hero container"><p class="eyebrow">Wixal for Mac</p><h1>Local AI for<br>your projects.</h1><p class="hero-subtitle">Ask a question, work with your files, and review the actions your model takes. Together on your Mac.</p><div class="hero-actions">${button(dmg)}${link(repo,'View source')}</div><p class="release-meta">${version} · Electron download · Apple Silicon · macOS 14+</p><figure class="workspace-preview"><button data-preview aria-label="Enlarge native workspace preview"><img src="${assetUrl('assets/native-workspace.png')}" alt="Native Wixal development preview showing Chat, Agents, Cybersecurity, project navigation and a quiet new conversation." width="1840" height="1344" fetchpriority="high" decoding="async"></button><figcaption><span>Native workspace · local development preview</span><button data-preview>View full size ↗</button></figcaption></figure></section><section class="section container"><h2>A workspace for the work.</h2><div class="capabilities">${row('models','Your models','Use the bundled local engine or an external Ollama server. Choose a model that fits your Mac and your task.',url('models/'),'Models & connections')}${row('projects','Your project','Keep files, conversations and useful context together. Read code, make reviewed edits, and run commands from your project.',url('product/'),'Inside the workspace')}${row('actions','Reviewed actions','Choose enabled tools, review requested actions, and inspect the returned evidence.',url('tools/'),'Tools & workflows')}</div></section><section class="section container native-section"><div><p class="eyebrow">In development</p><h2>The native workspace.</h2></div><div><p>A separate SwiftUI and Python app is in development, with Chat, Agents and Cybersecurity workflows. The image above shows the local preview.</p><p>The public ${version} download is the Electron app. The native preview is still undergoing workflow and accessibility acceptance.</p>${link(`${repo}/blob/main/native/README.md`,'Explore the native source')}</div></section>`;
const product = `${heading('Your project, in context.','Files, conversations and useful notes, close to the work.')}<section class="section container capabilities">${row('desktop','A workspace on your Mac','Open a project folder, attach useful files, and ask questions with a local model.',`${docs}/user-guide.md`,'Everyday use')}${row('connections','Choose your model','The bundled Wixal Local engine runs on your Mac. An external Ollama server is also supported.',url('models/'),'Model setup')}${row('memory','Useful context','Project notes, earlier conversations and visible summaries help carry decisions forward. Memory scope and saved notes are editable.',`${docs}/memory.md`,'Context and memory')}${row('terminal','A real terminal','Run commands in your project. Reviewed agent sessions return output and status to the conversation; the manual terminal supports interactive work.',url('tools/#commands'),'Command workflows')}${row('tools','Tools you choose','Enable file, web, API and trusted MCP tools, then review their requested actions.',url('tools/'),'Explore tools')}${row('companion','Optional companion connection','The Electron app supports a developer companion connection to ChatGPT for selected project context. It requires separate tunnel access and developer mode. Native companion delivery remains deferred.',`${docs}/connections.md`,'Connections guide')}</section>`;
const toolsPage = `${heading('Let the model work with you.','Choose available tools. Review an action. Read the result.')}<section class="section container capabilities">${row('selection','Choose the next step','Use a tool-capable model and enable the tools your task needs. Use @ to select a tool. Actions follow the workspace approval policy; disabled tools remain unavailable.',`${docs}/tool-workflows.md`,'Workflows and limits')}${row('files','Project files','Read and search files, create folders, and review proposed writes or exact text replacements within your project.',`${docs}/features.md`,'File tools')}${row('commands','Commands with evidence','Start a reviewed command, read output and exit status, send input, and stop a running session. Retain useful output as a project record.',`${docs}/cyber-tools.md#command-sessions`,'Command sessions')}${row('web','Websites and APIs','Retrieve source snippets, inspect rendered pages, or read HTTP and JSON responses. Network requests require a connection. Browser controls and session limits are documented.',`${docs}/tool-workflows.md`,'Web workflows')}${row('assessments','Authorised assessments','Run bounded website checks or Nmap profiles against systems you have permission to test. Review observations and returned evidence before drawing conclusions. Nmap requires a local installation.',`${docs}/website-assessments.md`,'Website assessments')}${row('external','Trusted MCP tools','Connect a local MCP server, discover its tools, and choose which tools the model can call. Connecting runs the server executable with your Mac account’s access.',`${docs}/features.md#external-mcp-tools`,'MCP setup')}</section><section class="section container prompts"><h2>Try a small task.</h2><p>Example prompts for a project with the relevant tools enabled.</p><ul><li>Explain this project’s structure and where I should start.</li><li>Read the test output and help me understand the failure.</li><li>Inspect this API response and summarise the useful fields.</li></ul></section>`;
const modelPage = `${heading('Choose a model for the work.','Local inference, with a library you control.')}<section class="section container capabilities">${row('local','Wixal Local is included','Open Models in the Electron app to download a model or import compatible installed Ollama weights. Model weights are downloaded separately; no model weights are bundled.',`${docs}/local-runtime.md`,'Local runtime guide')}${row('external','External Ollama','Connect a compatible Ollama server when you want to use a separately managed library.',`${docs}/connections.md`,'Connection setup')}${row('capabilities','Match the task','Choose a tool-capable model for actions and a vision-capable model for images. Capabilities depend on the selected model. Tools and network connections have their own requirements.',`${docs}/user-guide.md`,'Choosing a model')}${row('performance','Measure on your Mac','Compare reported generation speed, first-output timing and estimated memory fit. Benchmarks measure throughput on your device; they do not establish answer quality.',`${docs}/performance.md`,'Usage and benchmarks')}${row('switching','Keep the conversation','Finish or stop the current response before switching models. Readable chat and project context are retained, with foreign private reasoning and tool metadata excluded where required.',`${docs}/memory.md#switch-models-within-a-chat`,'Model switching')}</section>`;
const resourceRows = [
 ['Getting started','Projects, conversations and everyday use.','user-guide.md'],
 ['Tools & workflows','File edits, browser sessions and returned evidence.','tool-workflows.md'],
 ['Models & runtime','Downloads, imports and local inference.','local-runtime.md'],
 ['Context & memory','Project notes, scopes and conversation handoff.','memory.md'],
 ['Website assessments','Bounded checks and saved evidence.','website-assessments.md'],
 ['Cybersecurity tools','Commands, network profiles and local fixtures.','cyber-tools.md'],
 ['Accounts','Optional accounts and data boundaries.','accounts.md'],
 ['Connections','External Ollama and developer companion setup.','connections.md'],
 ['Development','Source builds, packaging and checks.','development.md'],
 ['Architecture','How the workspace fits together.','architecture.md']
];
const resources = `${heading('A place to start.','Learn the app, find a workflow, or build on the source.')}<section class="section container resource-list">${resourceRows.map(([title,copy,path])=>`<a class="resource-item" href="${docs}/${path}"><h2>${title}</h2><p>${copy}</p><span aria-hidden="true">↗</span></a>`).join('')}<a class="resource-item" href="${repo}/blob/main/CONTRIBUTING.md"><h2>Contributing</h2><p>Report an issue or propose a change.</p><span aria-hidden="true">↗</span></a></section><section class="section container" id="releases"><h2>What’s changed.</h2><p>Read the release notes for ${version}, or browse the full changelog.</p><div class="hero-actions">${link(release,'Latest release')}${link(`${repo}/blob/main/CHANGELOG.md`,'Changelog')}</div></section>`;
const download = `${heading('Wixal for your Mac.','The local engine is included. Choose your model after installing.')}<section class="section container download-layout"><div class="download-panel"><p class="eyebrow">Electron app · ${version}</p><h2>Download for macOS.</h2><p>Apple Silicon · macOS 14 or newer</p><div class="hero-actions">${button(dmg,'Download DMG')}${button(zip,'Download ZIP','secondary')}</div><p>No model weights are bundled. Intel Mac, Windows and Linux builds are unavailable in this release.</p>${link(release,'Release notes')}</div><div class="steps"><h2>Start with one project.</h2><ol><li>Open the DMG and drag Wixal into Applications.</li><li>Open Models and download a model, or import compatible installed Ollama weights.</li><li>Open a project folder and ask a question or describe a task.</li><li>Review requested actions and inspect the results.</li></ol><p class="note">This preview is not Developer ID signed or notarised. See the <a href="${release}">installation notes</a> if macOS blocks the first launch.</p>${link(`${docs}/user-guide.md`,'User guide')}</div></section><section class="section container native-section"><div><p class="eyebrow">Separate local preview</p><h2>Native development.</h2></div><div><p>The SwiftUI/Python preview is built from source. It is still undergoing acceptance testing and has no public native download in this release.</p>${link(`${repo}/blob/main/native/README.md`,'Native source and setup')}</div></section>`;
const privacy = `<section class="hero page-hero container"><h1>Website privacy.</h1><p class="hero-subtitle">Choose whether to share analytics.</p></section><section class="container section privacy-copy"><h2>Optional website analytics</h2><p>With your permission, this website uses Google Analytics to measure page visits, approximate visitor counts, referrals, and clicks on Wixal release downloads. Google receives browser and device information and processes your IP address. Analytics cookies distinguish browsers; these counts do not identify individual people.</p><p>Google Analytics loads only after you choose Allow analytics. You can change your choice using Analytics preferences in the footer. Declining keeps website analytics off. Downloads and all site pages remain available.</p><h2>Download clicks and GitHub downloads</h2><p>A download click records a request to open a release file. It does not prove a completed download or an installation. GitHub independently counts downloads of release assets, including direct links outside this site and repeated downloads.</p><h2>Public visitor total</h2><p>The site publishes only the aggregate active-user count for the last 30 days and the report update time. This count covers visitors who allow analytics and can be affected by browser blocking and Google processing delays. It updates daily.</p><h2>Your desktop workspace</h2><p>This website integration does not add telemetry to the Wixal app or send your projects, prompts, chats, model output, or notes to Google Analytics.</p><p><a class="inline-link" href="https://policies.google.com/privacy">Google privacy policy</a> · <a class="inline-link" href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub privacy statement</a></p></section>`;
const stats = `<section class="hero page-hero container"><h1>Wixal activity.</h1><p class="hero-subtitle">Downloads and website visitors.</p></section><section class="container section"><p class="note">These are downloads of DMG and ZIP release files, including direct GitHub downloads. Repeat downloads count again. Downloads do not equal unique users, installations, or active app users.</p><p role="status" data-stats-status>Loading GitHub release counts…</p><noscript><p>Enable JavaScript to load current counts, or view the release files on GitHub.</p></noscript>${totals()}<div class="stats-grid" style="grid-template-columns:1fr"><article class="download-panel"><h2 data-stats-latest>—</h2><p>Latest published release</p></article></div><div class="stats-table-wrap"><table class="stats-table"><thead><tr><th>Release</th><th>DMG</th><th>ZIP</th><th>Total</th></tr></thead><tbody data-stats-rows></tbody></table></div><p class="note">Website visitors and download clicks are measured separately in the owner’s Google Analytics account when visitors allow analytics. Repository visitors and clones are available in GitHub Insights.</p><div class="hero-actions">${link(repo+'/releases','View releases',external)}${link(repo+'/tree/wixal-metrics','Daily GitHub report',external)}${link(repo+'/graphs/traffic','Repository traffic (owner access)',external)}</div></section>`;

const pages = [
 {path:'',title:'Wixal — Local AI for your projects',description:'A local AI workspace for Mac. Ask questions, work with project files and review model actions.',content:home},
 {path:'product/',title:'Workspace — Wixal',description:'Project files, conversations, context and commands in Wixal.',content:product},
 {path:'tools/',title:'Tools & workflows — Wixal',description:'Reviewed file, command, web and MCP tools.',content:toolsPage},
 {path:'models/',title:'Models & connections — Wixal',description:'Local models, imports and benchmarks on your Mac.',content:modelPage},
 {path:'resources/',title:'Guides — Wixal',description:'Get started with Wixal and explore its workflows.',content:resources},
 {path:'download/',title:'Download for Mac — Wixal',description:`Wixal ${version} Electron download for Apple Silicon Macs running macOS 14 or newer.`,content:download},
 {path:'privacy/',title:'Website privacy — Wixal',description:'Optional website analytics and your choices.',content:privacy},
 {path:'stats/',title:'Download stats — Wixal',description:'GitHub release download counts and opted-in website visitors.',content:stats}
];
function document(page) {
  const canonical = `${origin}${url(page.path)}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.description}"><meta name="ga-measurement-id" content="${measurementId}"><meta name="theme-color" content="#f4f3ef"><meta property="og:type" content="website"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin}${assetUrl('assets/social-card.png')}"><meta name="twitter:card" content="summary_large_image"><link rel="canonical" href="${canonical}"><link rel="icon" href="${url('assets/favicon.svg')}" type="image/svg+xml"><script>try{const t=localStorage.getItem("wixal-site-theme");if(t==="dark"||t==="light")document.documentElement.dataset.theme=t}catch{}</script><link rel="stylesheet" href="${assetUrl('styles.css')}"><script type="module" src="${assetUrl('site.js')}"></script><script type="module" src="${assetUrl('analytics.js')}"></script>${page.path === 'stats/' ? `<script type="module" src="${assetUrl('totals.js')}"></script>` : ''}${page.path === 'stats/' ? `<script type="module" src="${assetUrl('stats.js')}"></script>` : ''}</head><body>${header(page.active)}<main id="main">${page.content}</main>${footer()}<aside class="analytics-choice" data-analytics-choice aria-label="Website analytics preferences" hidden><p>Allow optional analytics to help us understand website visits and download clicks? <a href="${url('privacy/')}">Privacy details</a></p><div><button data-analytics-deny>Decline</button><button data-analytics-allow>Allow analytics</button><button data-analytics-close aria-label="Close analytics preferences" hidden>Close</button></div></aside><dialog class="preview-dialog" aria-label="Wixal screenshot preview"><div class="preview-toolbar"><p>Inside Wixal</p><button data-preview-close aria-label="Close screenshot preview">Close ×</button></div><div class="preview-image"><img alt=""></div><p class="preview-description"></p></dialog></body></html>`;
}
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
await cp(resolve(root, 'public'), out, { recursive: true });
for (const file of ['styles.css', 'site.js', 'analytics.js', 'stats.js', 'totals.js']) await cp(resolve(root, 'src', file), resolve(out, file));
for (const page of pages) {
  await mkdir(resolve(out, page.path), { recursive: true });
  await writeFile(resolve(out, page.path, 'index.html'), document(page));
}
await writeFile(resolve(out, '404.html'), document({path:'404.html',title:'Page not found — Wixal',description:'Find your way back to Wixal.',content:`<section class="container error-page"><h1>This page has moved on.</h1><p>Let’s get you back to the workspace.</p>${button(url(''), 'Back to Wixal', '', arrow)}</section>`}));
await writeFile(resolve(out, '.nojekyll'), '');
await writeFile(resolve(out, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${origin}${url('sitemap.xml')}\n`);
await writeFile(resolve(out, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p => `<url><loc>${origin}${url(p.path)}</loc></url>`).join('')}</urlset>`);
await writeFile(resolve(out, 'assets/favicon.svg'), '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 124 110"><rect width="124" height="110" rx="16" fill="#26251e"/><path d="M9 19H25L41 66L54 31H68L82 66L98 19H114L92 87Q91 91 86 91H79Q74 91 73 87L61 54L49 87Q47 91 42 91H35Q31 91 29 87Z" fill="#f4f3ef"/></svg>');
console.log(`Built ${pages.length} Wixal pages at ${out} (base ${base}).`);
