const { _electron: electron } = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
const sharp = require('sharp');
const root = path.resolve(__dirname, '..');
(async () => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'wixal-app-'));
  const project = path.join(temp, 'Wixal demo');
  await fs.mkdir(project);
  await fs.writeFile(path.join(project, 'README.md'), '# Wixal demo\nA small project for testing the Wixal desktop app.\n');
  await fs.writeFile(path.join(project, '.env'), 'DO_NOT_SHOW=fixture');
  for (const format of ['jpeg', 'webp']) await sharp({ create: { width: 64, height: 64, channels: 3, background: '#e9a5bd' } }).toFormat(format).toFile(path.join(temp, `fixture.${format}`));
  const env = { ...process.env, WIXAL_DATA_DIR:path.join(temp, 'data'), WIXAL_TEST_PROJECT:project };
  delete env.ELECTRON_RUN_AS_NODE;
  let app;
  try {
    app = await electron.launch({ args:[root], env, ...(process.env.WIXAL_APP_PATH ? { executablePath:process.env.WIXAL_APP_PATH } : {}), timeout:30000 });
    const page = await app.firstWindow();
    async function openWorkspace(id) { if (!(await page.locator(id).isVisible())) await page.click('#workspace-menu-toggle'); await page.click(id); }
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') console.log('RENDERER:', message.text()); });
    await page.locator('#connection-label').filter({ hasText:'Ollama connected' }).waitFor({ timeout:15000, state: 'attached' });
    await page.locator('#project-label').filter({ hasText:'Wixal demo' }).waitFor();
    await fs.mkdir(path.join(root, 'artifacts'), { recursive:true });
    async function capture(name) { await page.locator('#toast').waitFor({ state: 'hidden', timeout: 10000 }); await page.screenshot({ path: path.join(root, `artifacts/${name}.png`) }); }
    await capture('wixal-desktop');
    console.log('PASS: app window, local models and project loaded');
    await page.click('#model-button');
    await page.locator('.model-row').filter({ hasText: 'Images' }).first().waitFor();
    await capture('wixal-models');
    await page.fill('#model-search', 'gemma');
    assert.equal(await page.locator('.model-row').count(), 1);
    await page.locator('.model-row').click();
    assert.equal(await page.locator('#mode-label').textContent(), 'Chat');
    await page.click('#mode-button');
    await page.locator('#models-dialog[open]').waitFor();
    await page.fill('#model-search', 'qwen');
    await page.locator('.model-row').click();
    await page.click('#mode-button');
    assert.equal(await page.locator('#mode-label').textContent(), 'Agent');
    await page.click('#model-button');
    await page.selectOption('#context-size', '8192');
    await page.waitForFunction(async () => (await window.wixal.state()).contextSize === 8192);
    await page.selectOption('#context-size', '16384');
    await page.click('[data-close="models-dialog"]');
    console.log('PASS: searchable models, capability-aware mode and saved context settings');
    await openWorkspace('#toolkit-button');
    await page.locator('[data-tool="run_command"]').uncheck();
    await page.waitForFunction(async () => !(await window.wixal.state()).enabledTools.includes('run_command'));
    await capture('wixal-toolkit');
    await page.locator('[data-tool="run_command"]').check();
    await page.click('#close-toolkit');
    await openWorkspace('#files-button');
    await page.locator('[data-file="README.md"]').waitFor();
    assert.equal(await page.locator('[data-file=".env"]').count(), 0);
    await page.click('[data-file="README.md"]');
    await page.locator('#file-content').filter({ hasText: 'A small project' }).waitFor();
    await capture('wixal-files');
    await page.click('#use-file');
    assert.match(await page.inputValue('#prompt'), /File context: README.md/);
    await page.fill('#prompt', '');
    await page.click('#conversation-label'); await page.fill('#rename-input', 'Working on Wixal');
    await page.locator('#rename-form button').click();
    await page.fill('#session-search', 'Working'); assert.equal(await page.locator('.session-item').count(), 1);
    await page.fill('#session-search', 'missing'); assert.equal(await page.locator('.session-item').count(), 0);
    await page.fill('#session-search', '');
    console.log('PASS: tool settings, protected file listing, previews, prompt context and conversation names');
    await app.evaluate(({ dialog }) => { globalThis.originalWixalDialog = dialog.showOpenDialog; });
    async function attachIcon() {
      await app.evaluate(({ dialog }, imagePath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [imagePath] }); }, path.join(root, 'assets/icon.png'));
      await page.click('#attach-image'); await page.locator('.attachment').waitFor();
      await app.evaluate(({ dialog }) => { dialog.showOpenDialog = globalThis.originalWixalDialog; });
    }
    await attachIcon();
    assert.match(await page.locator('.attachment').textContent(), /icon.png/);
    await page.locator('[data-remove]').click();
    assert.equal(await page.locator('.attachment').count(), 0);
    await app.evaluate(({ dialog }, folder) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [`${folder}/fixture.jpeg`, `${folder}/fixture.webp`] }); }, temp);
    await page.click('#attach-image');
    await page.waitForFunction(() => document.querySelectorAll('.attachment').length === 2);
    assert.ok((await page.locator('.attachment img').first().getAttribute('src')).startsWith('data:image/png;base64,'));
    await app.evaluate(({ dialog }) => { dialog.showOpenDialog = globalThis.originalWixalDialog; });
    await page.locator('[data-remove]').first().click(); await page.locator('[data-remove]').first().click();
    console.log('PASS: PNG, JPEG and WebP import, local thumbnails and removal');
    await openWorkspace('#memory-button');
    await page.fill('#memory-input', 'The project codename is moon-orchid-72.');
    await page.locator('#memory-form button').click();
    await page.locator('.memory-entry').filter({ hasText:'moon-orchid-72' }).waitFor();
    await page.click('#close-memory');
    console.log('PASS: project memory saved through UI');
    await openWorkspace('#terminal-button');
    await page.locator('#terminal .xterm').waitFor();
    const output = await page.evaluate(() => new Promise(async resolve => {
      let output = '';
      const remove = window.wixal.onEvent(event => {
        if (event.type === 'terminal') { output += event.text; if (output.includes('WIXAL_PTY_VERIFIED')) { remove(); resolve(output); } }
      });
      await window.wixal['terminal-write']("export PS1='wixal % '; clear; printf 'WIXAL_PTY_%s\\n' VERIFIED\r");
      setTimeout(() => { remove(); resolve(output); }, 10000);
    }));
    assert.match(output, /WIXAL_PTY_VERIFIED/);
    await capture('wixal-terminal');
    await page.click('#close-terminal');
    console.log('PASS: real zsh PTY accepted input and returned output');
    if (!process.env.WIXAL_SKIP_MODEL_TEST) {
      await attachIcon();
      await page.evaluate(() => { window.wixalSmokeDone = false; window.wixal.onEvent(event => { if (event.type === 'done') window.wixalSmokeDone = true; }); });
      await page.fill('#prompt', 'Use the write_file tool to create proof.txt containing exactly wixal-live-tool-ok. Do not use run_command. After the tool succeeds, reply with the project codename from memory and describe the attached icon in one short sentence.');
      await page.click('#send');
      await page.locator('#approval-dialog[open]').waitFor({ timeout:240000 });
      assert.match(await page.locator('#approval-title').textContent(), /proof.txt/);
      await page.click('#approve');
      await page.waitForFunction(() => window.wixalSmokeDone, undefined, { timeout:240000 });
      assert.equal((await fs.readFile(path.join(project, 'proof.txt'), 'utf8')).trim(), 'wixal-live-tool-ok');
      assert.match(await page.locator('#messages').textContent(), /moon-orchid-72/);
      await capture('wixal-agent');
      assert.equal(await page.locator('.message-images img').count(), 1);
      assert.match(await page.locator('#messages').textContent(), /letter|monogram|pink|dark|white|icon|w\b/i);
      await page.locator('.message-images button').click();
      await page.locator('#image-dialog[open]').waitFor();
      await page.click('[data-close="image-dialog"]');
      await page.locator('.copy-message').last().click();
      assert.match(await app.evaluate(({ clipboard }) => clipboard.readText()), /moon-orchid-72/);
      console.log('PASS: real local model requested a file write with an image, UI approval saved it, model recalled project memory and described the icon');
    }
    await page.reload();
    await page.locator('#connection-label').filter({ hasText:'Ollama connected' }).waitFor({ state: 'attached' });
    assert.equal(await page.locator('#memory-count').textContent(), '1');
    if (!process.env.WIXAL_SKIP_MODEL_TEST) assert.match(await page.locator('#messages').textContent(), /moon-orchid-72/);
    assert.equal(await page.locator('#conversation-label').textContent(), 'Working on Wixal');
    assert.equal((await page.evaluate(() => window.wixal.state())).contextSize, 16384);
    if (!process.env.WIXAL_SKIP_MODEL_TEST) assert.equal(await page.locator('.message-images img').count(), 1);
    await app.evaluate(() => { globalThis.originalWixalFetch = globalThis.fetch; globalThis.fetch = async () => { throw new Error('offline fixture'); }; });
    await openWorkspace('#refresh-models'); await page.locator('#connection-label').filter({ hasText: 'Ollama offline' }).waitFor({ state: 'attached' });
    await page.click('#model-button'); await page.locator('#ollama-help').waitFor();
    await app.evaluate(() => { globalThis.fetch = globalThis.originalWixalFetch; });
    await page.click('#model-refresh'); await page.locator('.model-row').first().waitFor(); await page.click('[data-close="models-dialog"]');
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(920, 640));
    await page.waitForFunction(() => window.innerWidth <= 920);
    const send = await page.locator('#send').boundingBox();
    assert.ok(send.y > 0 && send.y + send.height <= 640);
    await capture('wixal-compact');
    assert.deepEqual(errors, []);
    console.log('PASS: image persistence, offline recovery, clipboard and compact window layout');
    console.log('PASS: reload retained conversation and memory; no renderer exceptions');
    console.log('Screenshots saved in artifacts/.');
  } finally { if (app) await app.close(); await fs.rm(temp, { recursive:true, force:true }); }
})().catch(error => { console.error(error); process.exitCode = 1; });
